import {
  Home,
  User2,
  Contact,
  FlaskConical,
  Terminal,
  GraduationCap,
  Moon,
  Sun,
  LayoutGrid,
  GithubIcon,
  LinkedinIcon,
  Mouse,
  ArrowDown,
  FileUpIcon,
} from "lucide-react"

export const Icons = {
  home: Home,
  user: User2,
  contact: Contact,
  exp: FlaskConical,
  code: Terminal,
  learning: GraduationCap,
  moon: Moon,
  sun: Sun,
  layoutGrid: LayoutGrid,
  gitHub: GithubIcon,
  linkedin: LinkedinIcon,
  mouse: Mouse,
  arrowDown: ArrowDown,
  fileUp: FileUpIcon,
}